### ISSUE TITLE
Add multiple doorbell trigger cards for DoorBird devices with more than 1 button

### ISSUE THREAD

**Issue by newatschoen** [jghaanstra/com.doorbird#10]
I have already added my doorbird with apiuser1 in my homey. So far so good.

But when I try to add the same doorbird with another api user account it does not work

During the adding process (enter ip, username, password) the connection test is successful - but if I try to add the device nothing happens

**Comment by jghaanstra** [comment]
I initially thought you wanted to add a second DoorBird but I understand now you want to add the same DoorBird but with a different api user. I'm not sure why you would want to do this but it's not supported. 

The device is registered with the MAC address as identifier and it will not allow you to register two devices with the same identifier. Error handling should have been better but this is a corner case scenario.

Unless you can give me a very good reason why adding two device instances of the same DoorBird is a good idea I'm closing this issue.

**Comment by newatschoen** [comment]
Hi Jelger,

thank you very much for your quick response.

In our house live our parents and therefore also use one of the two Doorbird bell buttons. So that they hear the bell in other rooms, the ringing signal should be routed by Doorbird via webhook to a neo coolcam doorbell. For this I have created a second Doorbird-API user in Doorbird, which I would like to use now quite normally in the homey.

**Comment by jghaanstra** [comment]
Which DoorBird do you have? Perhaps it's possible to create different trigger cards for each button. This way you do not need to duplicate the device.

**Comment by newatschoen** [comment]
this sounds great - I use the D2102V :)

**Comment by jghaanstra** [comment]
Do you have seperate HTTP calls for both buttons in the DoorBird smartphone app?

**Comment by newatschoen** [comment]
you can add as many http calls as you want inside the doorbird app - it is a "central administration point" inside the doorbird smartphone app

means we need seperate (extra) http calls for the second button :)

**Comment by newatschoen** [comment]
inside the administration of the doorbird app I can set what happens if button 2 is pressed - e.g. http call "xy" will be executed

**Comment by jghaanstra** [comment]
Ok, I'll see if I can come up with something for this in a future release.

**Comment by newatschoen** [comment]
thx a lot :)

**Comment by jghaanstra** [comment]
This has been added with release 3.0.1.
