### ISSUE TITLE
Cannot install Doorbird app on Homey (version 2.1.2)

### ISSUE THREAD

**Issue by Vinzz46** [jghaanstra/com.doorbird#11]
Last week i did for the first time a factory reset on Homey ( early 2018).
Now i cannot install the Doorbird app on Homey anymore.
It says: "This app is incompatible with your Homey software version".
I am running Homey Version 2.1.2 and Homey app version 2.3.2.307.
How can it be fixed so i'll be able to install the Doorbird app on Homey?

**Comment by jghaanstra** [comment]
You have three choices.

Upgrade to experimental releases 2.2.x
Wait till 2.2.x is released to stable (which wont take long anymore I think)
Install an older version of the DoorBird app using the command line
