### ISSUE TITLE
Flow: Can’t select relais in action card

### ISSUE THREAD

**Issue by JustThe2ofUs** [jghaanstra/com.doorbird#13]
When creating a flow such as below (1,2,3,4) there’s no relais showing up to select. 

Furthermore I found out when using the action card “ask to open door” there’s no possibility to select at all which door / Relais.  (5)

![42724D66-977C-4B7E-9A3B-23E63FE8E3DE](https://user-images.githubusercontent.com/45788142/60275886-de47bc80-98fa-11e9-9964-35f90919f2f4.png)
![43203EA3-D0D1-4AA4-B0EB-E97292EE190C](https://user-images.githubusercontent.com/45788142/60275887-de47bc80-98fa-11e9-8da7-a81f91e58be9.png)
![4929867E-F04D-412D-9970-3BF9E4E160E9](https://user-images.githubusercontent.com/45788142/60275890-de47bc80-98fa-11e9-8507-77a9b5435971.png)
![DACA9D3B-B33D-42AC-8ADE-D9B6AB140C83](https://user-images.githubusercontent.com/45788142/60275891-dee05300-98fa-11e9-9d20-7853ea813f1d.png)

![1E2E079B-FE94-4818-A50A-11277256759F](https://user-images.githubusercontent.com/45788142/60276022-21099480-98fb-11e9-8187-b611f6e72dab.png)

**Comment by jghaanstra** [comment]
What DoorBird type do you have? And could you post a screenshot of the DoorBird mobile app "Administrator Settings > Relays" as well.

**Comment by JustThe2ofUs** [comment]
It’s the D101S. 
Trying to add the screen of the Relais setting on admin plus a screen of the in-app-action when pushing the key button, once I found out how to. 😁🙈

**Comment by jghaanstra** [comment]
Ok, nothing strange there. Could you send me a screenshot from the permissions of the user you added during pairing of the DoorBird in Homey.

**Comment by JustThe2ofUs** [comment]
Got it!  
Looks like the DoorBird App on Homey lost the password! Entering it again enabled the live view and let’s me select the Relais.  
So in short: The App and the device we’re not really connected. Strange. But solved! :)
Thx for taking care so quickly and intensively!  

--  
// via mobile //

**Comment by jghaanstra** [comment]
Glad its solved
