### ISSUE TITLE
Get error message using relay

### ISSUE THREAD

**Issue by Steffster74** [jghaanstra/com.doorbird#14]
![IMG_1945](https://user-images.githubusercontent.com/53013822/61393600-9bf21980-a8c1-11e9-88ee-5f9cf795868e.jpg)
First thanks for the great app, had some issus with installing the device when trying to install the http commands via the instructions. I have installed them manually in the doorbirds http calls section (don't know if this is causing the problem). 3 calls for motion, doorbell and relay.
When I press the new relay button in Homey I get an error message see screendump.
Also the trigger to see if the relay is used doesn't seem to work. Doorbell and motion work fine!
Hope you can give me advice or know what the problem is.
Thanks Stephan

**Comment by jghaanstra** [comment]
Thanx for reporting, seems to be a bug in the code. I submitted a new version to the app store. Either wait until it's approved or use GitHub to do a command line install. I'm closing this for now. If it still does not work with version 2.3.3 just post here again.

**Comment by Steffster74** [comment]
Hi, the update fixed the button in the homey app, this works fine now.
But when I trigger relay from within the doorbird app the http relay event is not received by the Homey app. I have made a flow with the logic (true / false) when the door is opened. But this only works when I press the button in the homey doorbird app. Any ideas?

**Comment by Steffster74** [comment]
The http call url I have put in manually because I receive an error when I use the link in the installation
guide setup with the correct mac address of the doorbird like so:
http://192.168.1.46/api/app/com.doorbird/relays/DoorbirdMACadress/

**Comment by jghaanstra** [comment]
Fixed with 2.3.3.

The issue with notifications or known and I'll look into it when I get back from my holiday.
