### ISSUE TITLE
Instellen DoorBird notificatie URLs lukt niet

### ISSUE THREAD

**Issue by thebossbe** [jghaanstra/com.doorbird#15]
Hello,
I have the exact same problem as described in https://github.com/jghaanstra/com.doorbird/issues/9
I've successfully installed the Homey/Homebird app previously. Suddenly, I remarked that Homey flows using the push button of the Homebird did not start anymore. I then checked everything, but couldn't find any errors in the configuration so I reinstalled the Homebird app for Homey. I then:
1. Connected Homebird to Homey: OK
2. Checked if the Homebird user I use for the connection to Homey had API-Operator rights: OK
3. Went to the Homey/Homebird app configuration to add the HTTP URLs: ERROR
4. Checked in the Homebird configuration if there were any HTTP Calls entries: at first, there were, I've deleted them.
I've also tried to configure the HTTP URLs with both an Android and iOS device: both failed... Rebooting Homey and Homebird did not fix the issue either.
I'm using the latest version of both Homey and Doorbird app.
Can you point me in any direction?
Thanks!
Frederik.

**Comment by jghaanstra** [comment]
I'm currently on holiday so I won't be able to take a look at it in the next 3 weeks. There seems to be an issue with the DoorBird API. I might not be able to fix it but I'll know for sure in three weeks.

Just wondering, why did you delete the http calls when they where added in the first place?

**Comment by thebossbe** [comment]
Thanks for your answer. I've deleted the entries to be sure to start from scratch, to have a clean, new installation. 
Enjoy your holidays!

**Comment by jghaanstra** [comment]
This will be fixed in the next release which will be submitted to the app store some time this week.

**Comment by jghaanstra** [comment]
This has been fixed with release 2.3.4 which is pending approval in the app store.

https://github.com/jghaanstra/com.doorbird/releases/tag/2.3.4
