### ISSUE TITLE
Error 401 Instellen DoorBird notificatie HTTP URLs

### ISSUE THREAD

**Issue by marga18** [jghaanstra/com.doorbird#17]
Ben al een tijd aan het proberen om de doorbird te laten werken via Homey maar krijg steeds een error 401 bij het Instellen DoorBird notificatie HTTP URLs. Inmiddels heel het internet afgezocht hoe ik de doorbird kan installeren maar zonder succes. Op dit moment werkt het alleen via de app. Hopelijk kunnen jullie mij verder helpen.

**Comment by jghaanstra** [comment]
A 401 error means you are using incorrect login credentials. Double check the username and password you are using and make sure that user has the right permissions as descibed in the [support topic](https://community.athom.com/t/app-doorbird/115).

(and please use the support topic for support questions like these. Github is used for bugs and feature requests).
