### ISSUE TITLE
FeatureRequest: Enable discovery of devices on other networks

### ISSUE THREAD

**Issue by parm46** [jghaanstra/com.doorbird#18]
I have my intercom on a separate vlan to my homey which means currently the device cannot be found. This request is to allow intercoms to be added manually by specifying the IP address to connect to rather than use the discovery method

**Comment by jghaanstra** [comment]
Enabing a mDNS forwarder on the network will allow the Doorbird to be discovered over multiple networks. For people who use VLANs on a network that does not support this, this is still a nice to have feature.

**Comment by jghaanstra** [comment]
Fixed with release 3.0.1
