### ISSUE TITLE
Doorbird werkt niet meer met Homey wanneer handmatig ip adres is toegevoegd

### ISSUE THREAD

**Issue by jerroenbakker** [jghaanstra/com.doorbird#22]
"Kan de DoorBird automatisch worden gevonden op het netwerk tijdens het toevoegen? Als dit niet het geval is en je de DoorBird handmatig hebt toegevoegd obv het IP adres dan gaat dat niet meer werken. 

Athom heeft ervoor gekozen dat devices die niet zichtbaar zijn via hun discovery method als offline te markeren."

**Comment by jghaanstra** [comment]
I implemented a small workaround for these design choices made by Athom. Could you install the test version and let me know if this resolves the issue. You can install the regular app store version afterwards without any issues.

https://homey.app/a/com.doorbird/test/

**Comment by jerroenbakker** [comment]
I’ deleted the regular app and installed the test version. I can’t add a new flow card for Doorbird. Doorbird isn’t visible in the overview, see the following screenshot: https://postimg.cc/CBL5wZs3

**Comment by jghaanstra** [comment]
You should not have deleted the regular app but just install the test version over it. Now you probably need to (manually) repair your DoorBird.

**Comment by jerroenbakker** [comment]
What do you mean with "repair"? My Doorbird isn't broken. I will delete all Doorbird apps on Homey, will install the Doorbird app again and will install the testversion 'over it'.

**Comment by jerroenbakker** [comment]
Strange, deleted the Doorbird app. Re-install the normal version and can see the Doorbird app when configurating the new device. Case closed in my situation.
