### ISSUE TITLE
MAC not set correctly

### ISSUE THREAD

**Issue by RWensveen** [jghaanstra/com.doorbird#6]
To identify which Doorbird send a message to Homey, both ip-address and the MAC is used.
However, the MAC is not part of the device settings, but of the device data. Therefore, in the code, the doorbird-MAC is always compared to 'null'.
Same goes for setting the http-call messages (during pairing) in the doorbird. The MAC part of the written link contains 'null' in stead of the MAC.
As a result, the communication between Doorbird and the app on Homey fails.

Possible solutions
* add the 'id' (with the mac) to the device settings:
    - drivers/doorbird/pair/start.html, line 80 => add "id: inputmac"
* get the mac from the 'id' field in the device data
   - api.js, line 92 => replace "getSetting('id')" with "getData().id"
   - lib/util.js, line 21 => replace "getSetting('id')" with "getData().id"

I tested this with the 2nd solution, which works perfectly.

**Comment by jghaanstra** [comment]
Will be fixed with release 2.2.1 which has been submitted to the app store. Thanx for reporting and supplying the fix.

https://github.com/jghaanstra/com.doorbird/releases/tag/2.2.1
