### ISSUE TITLE
Motion or press or trigger = same?

### ISSUE THREAD

**Issue by gmax21** [jghaanstra/com.doorbird#7]
Hey there.

I've gone through setup a few times now, I must be missing something or there is a potential issue. I appreciate some assistance if this is me. :)

So... I set up a flow, if I select either Motion Detected, Door Opened or Doorbird Rings, they all respond to the motion, they all respond to trigger and also press.

![screen shot 2018-05-10 at 03 20 29](https://user-images.githubusercontent.com/1209520/39848825-1c9956f0-5401-11e8-8c2a-8e30a355de12.png)

So with the flow as per my screenshot, it will keep sending the push notification everytime someone walks by. Every time I hit the key button in the app. And every time you press the doorbell.

Am I doing something wrong? :(

**Comment by jghaanstra** [comment]
Have you followed the steps under " Setting up notifications” from the description in the Homey app store? The Doorbird company recently changed things around requiring the notifications to be setup again with some manual steps.

**Comment by gmax21** [comment]
I see what happened, it was indeed my own confusion. I went through the set up process a number of times too, so missed each time. 

My confusion was over the fact there are two schedules to set, one is the 3D Motion Sensor settings and the Schedule for doorbell.

Admin --> 3D Motion Sensor --> Settings --> Schedule for actions
Admin --> Schedule for doorbell

When inside the scheduling area they are both titled Schedule for actions. I think it's this that probably led to my confusion and then I couldn't understand why motion was triggering all three flows in Homey. I do see in your instructions now that you talk about both areas. :)

Thanks for your help and taking the time to respond, and thanks for the app, you're awesome! :)
