### ISSUE TITLE
Add relays as capabilities to make them available in mobile card

### ISSUE THREAD

**Issue by jghaanstra** [jghaanstra/com.doorbird#8]
Would require changes to pair wizard so devices and their number of relays are known.

**Comment by JustThe2ofUs** [comment]
Not sure if it’s the same here:
Open door can be selected as an Action-Card, but the list of relays is empty. 
Is this a bug due to homeys issue w/ selecting tags??

**Comment by jghaanstra** [comment]
> Not sure if it’s the same here:
> Open door can be selected as an Action-Card, but the list of relays is empty.
> Is this a bug due to homeys issue w/ selecting tags??

It's unrelated to this enhancements issue. You are the first to report it while the functionality has been in use for quite some time. That suggests its an issue on your end. Please use the support topic on the forum for this.

**Comment by JustThe2ofUs** [comment]
Hi and thx for answering so quickly. 
So to understand right:

Using the action card “open door” should then let me select the relays?

**Comment by jghaanstra** [comment]
Please open up a new issue and include screenshots of what you see. Your DoorBird type does have a Relay and it's named under the administration settings in the DoorBird mobile app?

**Comment by jghaanstra** [comment]
Added default relay as button capability so it shows up as button in the mobile app under the device in release 2.3.2. This version is awaiting approval in the app store.
