### ISSUE TITLE
Error “Instellen Doorbird notificatie HTTP URL’s”

### ISSUE THREAD

**Issue by KVKRTD** [jghaanstra/com.doorbird#9]
Good morning.

I want to configure the Doorbird app but it won’ allow me to. Clicking on “Instellen Doorbird notificatie HTTP URL’s” gives an error. Could you please advise what to do.

Thanks.

Koen

**Comment by jghaanstra** [comment]
Have you added your DoorBird as device as described in the instructions in the app store?

**Comment by KVKRTD** [comment]
Hi Jelger,

Als het goed is heb ik alle stappen doorlopen.

In doorbird heb ik een nieuwe user aangemaakt en deze gebruikt voor Homey.

Er gebeurd niks als ik op de button klik. Althans bij meerdere keren klikken krijg ik de volgende error:



Groet,

Koen

**Comment by jghaanstra** [comment]
What do you see in the DoorBird smartphone app under administration > http calls?

**Comment by KVKRTD** [comment]
It’s empty. I can click on add.

**Comment by jghaanstra** [comment]
And what is exactly the error that is show when you click on add notifications? It's seems you have not mentioned this yet.

**Comment by KVKRTD** [comment]
The issue is that in Homey when I want to configure the app it won’t allow me to select “instellen doorbird notificatie http urls”. Should this be clickable at all...?

**Comment by jghaanstra** [comment]
Yep, that should be clickable and I just tested it and it works fine for me on the Android Homey smartphone app.

Which app version, Homey version and smartphone Homey app version are you using?

**Comment by KVKRTD** [comment]
I’m using IOS app.
Homey App version: 2.0.6.250
Homey version: 2.0.2

**Comment by jghaanstra** [comment]
I really dont know what the problem is. Could you post a video or at least a screenshot on how the settings page looks like and how the device page looks like. Perhaps I can see something on there.

And do you know how to do a command line install. I could create a version here on GitHub with extra debug logging to see if I can figure out the problem.

**Comment by KVKRTD** [comment]
I made a screenrecording of both. How do you want me to share this with you?

I have no idea how to install a command line, sorry.

**Comment by jghaanstra** [comment]
Yes, please upload them here.

**Comment by KVKRTD** [comment]
[ScreenRecording_02-13-2019 08-13-07.zip](https://github.com/jghaanstra/com.doorbird/files/2859478/ScreenRecording_02-13-2019.08-13-07.zip)

**Comment by jghaanstra** [comment]
I'm clueless, and you seem to be the only one affected by this. Could it be you are blocking javascript or something on your phone?

**Comment by KVKRTD** [comment]
Not sure if it has something to do with my iphone. Via the Homey developer page I have the same issue with this button. Also the error apprears:
![homey doorbird](https://user-images.githubusercontent.com/47554050/52704901-ed4c5480-2f81-11e9-91d3-3fb0a8bd7821.png)

**Comment by jghaanstra** [comment]
In the video you send me you did not show me the actual DoorBird device which you should have added within Homey. Could you select your DoorBird within the Homey app, go to the advanced settings and make a screenshot there. Perhaps its something in the settings of the DoorBird.

And did you see a snapshot when you paired your DoorBird with Homey?

**Comment by KVKRTD** [comment]
![img_1102](https://user-images.githubusercontent.com/47554050/52707511-2a1b4a00-2f88-11e9-8229-ec67710a7650.PNG)

It's some time ago that I paired the Doorbird with Homey. But if I remember well I did see a snapshot when I paired it.

**Comment by jghaanstra** [comment]
This is in the description. Please re-pair your DoorBird and try again.

>For the doorbell alarm, motion alarm, doorbell rang, motion detected and door open trigger flow cards to work in Homey the DoorBird needs to be configured to send HTTP notifications based on these events to Homey. The DoorBird company recently changed they way this works (as of DoorBird firmware 0110). If you have added your DoorBird to Homey before 2018-02-20 follow these steps first.

Open the DoorBird smartphone app, go to the administration area and select the user you have used to add your DoorBird to Homey
Go the the permissions of this user and grant this user API-operator permissions
Go back and select the HTTP calls option under the Favorites section, delete all legacy HTTP calls containing your Homey IP address

**Comment by jghaanstra** [comment]
Closed due to inactivity / no response.

**Comment by JustThe2ofUs** [comment]
Though it’s closed:
I experienced the same issue and tried to click “add” many times; always gave me “error”. Then I left it be. And suddenly it worked 🤷‍♂️
